### ISSUE TITLE
swift版本兼容

### ISSUE THREAD

**Issue by youlianchun** [jkpang/PPBadgeView#14]
啥时候进行版本迁移？ 'Self' is only available in a protocol or as the result of a method in a class;

**Comment by jkpang** [comment]
你使用的Swift是什么版本，PPBadgeViewSwift 2.1.0在Swift 4.1环境下编译没有问题 @youlianchun

**Comment by youlianchun** [comment]
最新的，xcode10下，应该是swift4.2

**Comment by jlaws** [comment]
XCode 10 support requires line 36 of PPBadgeLabel to add the required keyword.  Can we get an updated podspec with the fix now that the Xcode 10 GM is out?  Thanks for the great library!

**Comment by damozhang** [comment]
@jlaws I have submit a pull request #15

**Comment by jkpang** [comment]
PPBadgeViewSwift release v2.2.0, support Xcode10 and Swift4.2，Thanks for feedback！ @jlaws @youlianchun 

Thanks @12789  for pull request.

![image](https://user-images.githubusercontent.com/17583451/45481436-17ed7380-b77e-11e8-8e37-5f607a561773.png)
