### ISSUE TITLE
The badgeview doesn't show up

### ISSUE THREAD

**Issue by sambo-visal** [jkpang/PPBadgeView#19]
`self.navigationItem.leftBarButtonItem = UIBarButtonItem.init(barButtonSystemItem: .add, target: self, action: nil)`
        `self.navigationItem.leftBarButtonItem?.pp.addBadge(number: 1)`
`self.navigationItem.leftBarButtonItem?.pp.addDot(color: UIColor.red)`
            `self.navigationItem.leftBarButtonItem?.pp.moveBadge(x: -5, y: 0)`
I do programmatically and when i run and i don't see the badge

**Comment by madhusudan7855** [comment]
Having same issue. Did you find any solution for that?

**Comment by sambo-visal** [comment]
Yes. But put them in dispatcheQueue

`let rightBarButton = UIBarButtonItem(image: UIImage(named: "notification")?.withRenderingMode(UIImageRenderingMode.alwaysOriginal), style: .plain, target: self, action: #selector(notificationHandle))
self.navigationItem.rightBarButtonItem = rightBarButton

if (UIDevice.current.systemVersion as NSString).doubleValue >= 11.0 {
    DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.01, execute: {
        rightBarButton.pp.addBadge(text: "99+")
        rightBarButton.pp.moveBadge(x: -5, y: 0)
        rightBarButton.pp.setBadge(height: 12)
        rightBarButton.pp.setBadge(flexMode: PPBadgeViewFlexMode.tail)
    })
} else {
    rightBarButton.pp.addBadge(text: "99+")
    rightBarButton.pp.moveBadge(x: -5, y: 0)
    rightBarButton.pp.setBadge(height: 12)
    rightBarButton.pp.setBadge(flexMode: PPBadgeViewFlexMode.tail)
}`
