### ISSUE TITLE
 non-public APIs

### ISSUE THREAD

**Issue by ChenYilong** [jkpang/PPBadgeView#2]
UITabBarSwappableImageView is non-public API, carefully use 

Reference: https://github.com/ChenYilong/CYLTabBarController/issues/147

**Comment by jkpang** [comment]
The relevant code for UITabBarSwappableImageView has been removed and the version updated to 1.1.0. Thank you very much for your contribution to the open source community! @ChenYilong

**Comment by YuanJiaShuai** [comment]
[rightbarBtn pp_addBadgeWithNumber:5]; 导航栏按钮设置未生效

**Comment by jkpang** [comment]
1. 断点调试下添加badge的时候rightbarBtn是否为nil ? 
2.贴出rightbarBtn的关键代码;
3.此问题可以重新开个issue.
 @YuanJiaShuai
