### ISSUE TITLE
Xcode10 'bringSubviewToFront' has been renamed to 'bringSubview(toFront:)

### ISSUE THREAD

**Issue by KevinYin2022** [jkpang/PPBadgeView#20]
Need to update method name.
'bringSubviewToFront' has been renamed to 'bringSubview(toFront:)

**Comment by jkpang** [comment]
Please use Swift 4.2 as the compiled version @xiaoleiyindd01

**Comment by lixiang1994** [comment]
+1 
<img width="1288" alt="wx20181008-185101 2x" src="https://user-images.githubusercontent.com/13112992/46605162-2cc5e880-cb2b-11e8-8b6e-cacf388b85a4.png">

**Comment by lixiang1994** [comment]
@jkpang

**Comment by lixiang1994** [comment]
.podspec Add s.swift_version = "4.2" , Please

**Comment by jkpang** [comment]
Version 2.2.2 has been released, and this problem has been fixed. @lixiang1994 @xiaoleiyindd01

**Comment by lixiang1994** [comment]
Thanks!
