### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [jkpang/PPBadgeView#27]
## Expected Results

No warning to convert PPBadgeViewSwift.framework to Swift 5

## Actual Results

Xcode created warnings to convert PPBadgeViewSwift.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by jkpang** [comment]
Hi, Version 3.0.0 has been released, warnings have been fixed, and code has been migrated to Swift5 @jlaws 

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by jlaws** [comment]
Thanks for the fast turnaround!
