### ISSUE TITLE
UIBarButtonItem 不显示角标

### ISSUE THREAD

**Issue by YuanJiaShuai** [jkpang/PPBadgeView#3]
@jkpang 你好，我使用一下代码
```
UIBarButtonItem * navRightButton = [[UIBarButtonItem alloc]initWithImage:[UIImage imageNamed:@"形状7"] style:UIBarButtonItemStylePlain target:self action:@selector(msgmanagerBtnEvent)];
    NSLog(@"navRightButton = %@", navRightButton);
//    [navRightButton pp_addBadgeWithNumber:10];
    self.navigationItem.rightBarButtonItem = navRightButton;
    [self.navigationItem.rightBarButtonItem pp_addBadgeWithNumber:10];
```
就不能正确显示角标，但是使用一下代码就可以正确显示
```
    UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
    [button setImage:[UIImage imageNamed:@"形状7"] forState:UIControlStateNormal];
    button.frame = CGRectMake(0,100,button.currentImage.size.width, button.currentImage.size.height);
    [button addTarget:self action:@selector(msgmanagerBtnEvent) forControlEvents:UIControlEventTouchDown];
    // 添加角标
    UIBarButtonItem *navRightButton = [[UIBarButtonItem alloc] initWithCustomView:button];
    self.navigationItem.rightBarButtonItem = navRightButton;
    // 添加角标
    [Manager getJiaoBiaoCount:^{
        [navLeftButton pp_addBadgeWithNumber:[USER_D integerForKey:mesCount]];
    }];

```

**Comment by jkpang** [comment]
经过测试: 
1. 如果先对navRightButton添加badge:  `[navRightButton pp_addBadgeWithNumber:10]`;
    后对rightBarButtonItem赋值:  `self.navigationItem.rightBarButtonItem = navRightButton` ;
    这样添加badge是不成功的,  

2. 如果先对rightBarButtonItem赋值:  `self.navigationItem.rightBarButtonItem = navRightButton`
    后对navRightButton添加badge: `[navRightButton pp_addBadgeWithNumber:10]`
    这样badge是可以添加成功的.

原因是: 
方式1中, 虽然navRightButton已被实例化,但其成员变量 UINavigationButton *_view == nil, 此时badge找不到父视图,所以无法添加 ; 
方式2中: 实例化出来的navRightButton并成功赋值给rightBarButtonItem(进过系统一系列的赋值操作), 此时navRightButton的成员变量 UINavigationButton *_view != nil, 所以 badge 可以找到父视图,也就可以成功添加.

你可以通过断点或打印log的方式来观察rightBarButtonItem赋值前后navRightButton内部属性的变化
 @YuanJiaShuai

**Comment by YuanJiaShuai** [comment]
@jkpang 谢谢你的提示

**Comment by jkpang** [comment]
不客气 😊

**Comment by ShareZore** [comment]
@YuanJiaShuai 关于barButtonItem不能正常显示的问题，不知有没有解决
