### ISSUE TITLE
iOS 9 tababr icon 飘了

### ISSUE THREAD

**Issue by CivelXu** [jkpang/PPBadgeView#30]
<img width="460" alt="WechatIMG7" src="https://user-images.githubusercontent.com/19768199/57227083-1b9e7500-7043-11e9-8461-3f6bf5b033b6.png">

如图所示

代码如下
```
    fileprivate func setBadge(num: String) {
        if let value = Int(num), value > 0 {
            self.viewControllers?.last?.tabBarItem.pp.addBadge(text: num)
        } else {
            self.viewControllers?.last?.tabBarItem.pp.hiddenBadge()
        }
    }
```

Swift5 + 3.0.0 版本 注释掉代码显示正常

**Comment by jkpang** [comment]
V3.1.0 has been released, this issue has been fixed, thanks for feedback
