### ISSUE TITLE
小圆点无法移除

### ISSUE THREAD

**Issue by xingfuqiu** [jkpang/PPBadgeView#6]
添加小圆点后无法移除
`viewController.tabBarItem.pp.addDot(color: .red)`
没有找到移除函数

**Comment by jkpang** [comment]
viewController.tabBarItem.pp.hiddenBadge()

![image](https://user-images.githubusercontent.com/17583451/38541916-0a17b62e-3cd3-11e8-94fe-690054928199.png)
@xingfuqiu
